/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Jens (https://sketchfab.com/excitedneon)
license: CC-BY-SA-4.0 (http://creativecommons.org/licenses/by-sa/4.0/)
source: https://sketchfab.com/3d-models/30days3d-day-3-mail-box-357acbf2a0d04aa591a7d71982af0436
title: #30Days3D - Day 3 - Mail Box
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/mail.gltf')
  return (
    <group rotation={[-1,90,0]} ref={group} {...props} dispose={null}>
      <group  rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Mailbox_0.geometry} material={materials.Red_Metal} />
        <mesh geometry={nodes.Mailbox_1.geometry} material={materials.Gray_Metal} />
        <mesh geometry={nodes.Letters_0.geometry} material={materials.Paper} />
      </group>
    </group>
  )
}

useGLTF.preload('/mail.gltf')
