/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Macd3d (https://sketchfab.com/Macd3d)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/percy-pigeon-b652c476dfeb46f283afb1b471bff652
title: Percy Pigeon
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/pigeon.gltf')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group  rotation={[-Math.PI / 2.50, 0, 0.7]} scale={2.54}>
        <group position={[-2.21, 0.91, 11.49]} rotation={[-0.03, 0, -3.11]} scale={-0.74} />
        <group position={[-2.37, -0.48, 11.49]} rotation={[2.74, 1.55, -2.78]} scale={0.74} />
        <group position={[0.09, 0, -0.1]} scale={0.11}>
          <mesh geometry={nodes.PRIG01_0047Percy_Mesh002_0.geometry} material={materials['Top_Beak.001']} />
        </group>
        <group position={[0.09, 0, -0.1]} scale={0.11}>
          <mesh geometry={nodes.PRIG01_0047Percy_Mesh001_0.geometry} material={materials['Wings.001']} />
        </group>
        <mesh geometry={nodes.PRIG01_0047R_Eye_LidB004_0.geometry} material={materials['Lids.001']} />
        <mesh geometry={nodes.PRIG01_0047L_Eye002_0.geometry} material={materials['Eye.001']} />
        <mesh geometry={nodes.PRIG01_0047L_Eye002_1.geometry} material={materials['Pupil.001']} />
        <mesh geometry={nodes.PRIG01_0047Percy_Mesh_0.geometry} material={materials['Percy.001']} />
      </group>
    </group>
  )
}

useGLTF.preload('/pigeon.gltf')
